server_info_path="zjzksvr.xiimoon.com"   #xiimoon server info hostname
res_server_path="dlres.xiimoon.com"   #xiimoon resource server
#res_server_path="zjzkgameres-1253640862.cossh.myqcloud.com"  #alternate resource server
platform_name="Android" #assets for which patform
#platform_name="IOS"
version="1.3.0_elite"  #version string
#version="1.1.0"
download_dir="./assets/"  #where to put the assets
verbose=False  #whether to display skipped files
thread=20